### ISSUE TITLE
Customize jquery.pep.js options

### ISSUE THREAD

**Issue by njosefbeck** [Sleavely/jquery-infinite-drag#6]
Hi!

I love that you've adapted Infinite Drag to use the jquery.pep.js library. I don't know if you're still working on this project, but I'd really like being able to pass some options into the pep library, to change the scrolling behavior. I'm mostly interested in being able to change the velocityMultiplier option. 

Do you have any recommendations about how I might go about passing options to pep? I've tried a couple of different things, but they haven't worked. I also have yet to dig into the infinite drag code itself, but that's my next step. Anyway, just thought I'd post and see if you had any ideas.

Thanks!

**Comment by Sleavely** [comment]
Hi Nathan!

It's been a while since I used this code myself, but if I recall correctly the infinitedrag method signature is something like `jQuery.infinitedrag(string Selector, object Pep-options, object Infinitedrag-options)`. I glanced quickly at the code and this seems to be correct.
